from unittest import TestCase


class Test(TestCase):
    def test_outer_function(self):
        self.fail()
